

const job_role = {
  UX_UI: "UX_UI",
  FRONTEND_DEVELOPER: "FRONTEND_DEVELOPER",
  BACKEND_DEVELOPER: "BACKEND_DEVELOPER",
  FULLSTACK: "FULLSTACK",
  DEVOPS: "DEVOPS",
  QUALITY_ASSURANCE: "QUALITY_ASSURANCE",
  SOFTWARE_DEVELOPER: "SOFTWARE_DEVELOPER",
  MOBILE_APP_IOS: "MOBILE_APP_IOS",
  MOBILE_APP_ANDROID: "MOBILE_APP_ANDROID",
  MOBILE_APP_HYBRID: "MOBILE_APP_HYBRID",
  BUSINESS_ANALYST: "BUSINESS_ANALYST",
  PRODUCT_MANAGER: "PRODUCT_MANAGER",
  PROJECT_MANAGER: "PROJECT_MANAGER",
  DATABASE_ADMIN: "DATABASE_ADMIN",
  INFORMATION_SECURITY: " INFORMATION_SECURITY",
};

const job_level = {
    INTERN: "INTERN",
    JUNIOR: 'JUNIOR',
    INTERMEDIATE: "INTERMEDIATE",
    SENIOR: "SENIOR",
    ADVANCE: "ADVANCE"
}

const job_type = {
    FULL_TIME: 'FULL_TIME',
    PART_TIME: 'PART_TIME',
    REMOTE: 'REMOTE',
    CONTRACT: "CONTRACT"
}

module.exports = {
    job_role,
    job_level,
    job_type
}
